### PR TITLE
readme: improve install, add example, make DOCKER_CONFIG_PATH required

### PR DESCRIPTION
**Pull request by mrjones-plip**

### CODE REVIEW

**Comment by lorerod** [comment]
Hi @mrjones-plip! Thanks for this documentation. I was following these steps and found that the user and password set in the .env file are not the ones defined by the upgrade service.

- Used the following compose files:

[cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic%3Amedic%3A4.0.0/docker-compose%2Fcht-core.yml)
[cht-couchdb.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic%3Amedic%3A4.0.0/docker-compose%2Fcht-couchdb.yml)
[cht-upgrade-service.yml](https://github.com/medic/cht-upgrade-service/blob/main/docker-compose.yml)

- Used the following env variables:

```
CHT_COMPOSE_PROJECT_NAME=4-test-upgrade-service
COUCHDB_SECRET=lorenapassword
DOCKER_CONFIG_PATH=${PWD}/compose
COUCHDB_DATA=${PWD}/couchd
CHT_COMPOSE_PATH=${PWD}/compose
COUCHDB_USER=lorena
COUCHDB_PASSWORD=lorenapassword
```

- Upgrade service finishes without errors. You can see in the logs that user and password are actually the default value defined in the cht-couchdb.yml (admin and password instead of lorena and lorenapassword). I can login with admin and password.

Please let me know if I can help with more information.


<details>
<summary>Upgrade service log:</summary>

```
% docker compose up     
[+] Running 8/8
 ⠿ cht-upgrade-service Pulled                                                                                                      16.7s
   ⠿ 9621f1afde84 Pull complete                                                                                                     1.5s
   ⠿ 17cb27c841b2 Pull complete                                                                                                     7.4s
   ⠿ a9cbc71018b1 Pull complete                                                                                                     7.6s
   ⠿ 2377ef6be762 Pull complete                                                                                                     7.7s
   ⠿ fcef55c4d6e6 Pull complete                                                                                                    13.0s
   ⠿ c07d03ffb4d3 Pull complete                                                                                                    13.1s
   ⠿ 7705c6b431d7 Pull complete                                                                                                    13.3s
[+] Running 2/2
 ⠿ Network cht-net                    Created                                                                                       0.1s
 ⠿ Container 4-cht-upgrade-service-1  Created                                                                                       0.5s
Attaching to 4-cht-upgrade-service-1
4-cht-upgrade-service-1  | Listening on port 5008
4-cht-upgrade-service-1  | .UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 1067: invalid start byte
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | .IsADirectoryError: [Errno 21] Is a directory: '/docker-compose/aws_conf'
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | networks:
4-cht-upgrade-service-1  |   cht-net:
4-cht-upgrade-service-1  |     name: cht-net
4-cht-upgrade-service-1  | services:
4-cht-upgrade-service-1  |   api:
4-cht-upgrade-service-1  |     depends_on:
4-cht-upgrade-service-1  |       haproxy:
4-cht-upgrade-service-1  |         condition: service_started
4-cht-upgrade-service-1  |     environment:
4-cht-upgrade-service-1  |       BUILDS_URL: https://staging.dev.medicmobile.org/_couch/builds
4-cht-upgrade-service-1  |       COUCH_URL: http://admin:password@haproxy:5984/medic
4-cht-upgrade-service-1  |       UPGRADE_SERVICE_URL: http://cht-upgrade-service:5008
4-cht-upgrade-service-1  |     expose:
4-cht-upgrade-service-1  |     - '5988'
4-cht-upgrade-service-1  |     image: public.ecr.aws/s5s3h4s7/cht-api:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  |     logging:
4-cht-upgrade-service-1  |       driver: local
4-cht-upgrade-service-1  |       options:
4-cht-upgrade-service-1  |         max-file: '20'
4-cht-upgrade-service-1  |         max-size: 50m
4-cht-upgrade-service-1  |     networks:
4-cht-upgrade-service-1  |       cht-net: null
4-cht-upgrade-service-1  |   haproxy:
4-cht-upgrade-service-1  |     environment:
4-cht-upgrade-service-1  |       COUCHDB_PASSWORD: password
4-cht-upgrade-service-1  |       COUCHDB_SERVERS: couchdb
4-cht-upgrade-service-1  |       COUCHDB_USER: admin
4-cht-upgrade-service-1  |       HAPROXY_IP: haproxy
4-cht-upgrade-service-1  |       HAPROXY_PORT: '5984'
4-cht-upgrade-service-1  |       HEALTHCHECK_ADDR: healthcheck
4-cht-upgrade-service-1  |     expose:
4-cht-upgrade-service-1  |     - '5984'
4-cht-upgrade-service-1  |     hostname: haproxy
4-cht-upgrade-service-1  |     image: public.ecr.aws/s5s3h4s7/cht-haproxy:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  |     logging:
4-cht-upgrade-service-1  |       driver: local
4-cht-upgrade-service-1  |       options:
4-cht-upgrade-service-1  |         max-file: '20'
4-cht-upgrade-service-1  |         max-size: 50m
4-cht-upgrade-service-1  |     networks:
4-cht-upgrade-service-1  |       cht-net: null
4-cht-upgrade-service-1  |   healthcheck:
4-cht-upgrade-service-1  |     environment:
4-cht-upgrade-service-1  |       COUCHDB_PASSWORD: password
4-cht-upgrade-service-1  |       COUCHDB_SERVERS: couchdb
4-cht-upgrade-service-1  |       COUCHDB_USER: admin
4-cht-upgrade-service-1  |     image: public.ecr.aws/s5s3h4s7/cht-haproxy-healthcheck:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  |     logging:
4-cht-upgrade-service-1  |       driver: local
4-cht-upgrade-service-1  |       options:
4-cht-upgrade-service-1  |         max-file: '20'
4-cht-upgrade-service-1  |         max-size: 50m
4-cht-upgrade-service-1  |     networks:
4-cht-upgrade-service-1  |       cht-net: null
4-cht-upgrade-service-1  |   nginx:
4-cht-upgrade-service-1  |     depends_on:
4-cht-upgrade-service-1  |       api:
4-cht-upgrade-service-1  |         condition: service_started
4-cht-upgrade-service-1  |       haproxy:
4-cht-upgrade-service-1  |         condition: service_started
4-cht-upgrade-service-1  |     environment:
4-cht-upgrade-service-1  |       API_HOST: api
4-cht-upgrade-service-1  |       API_PORT: '5988'
4-cht-upgrade-service-1  |       CERTIFICATE_MODE: SELF_SIGNED
4-cht-upgrade-service-1  |       COMMON_NAME: test-nginx.dev.medicmobile.org
4-cht-upgrade-service-1  |       COUNTRY: US
4-cht-upgrade-service-1  |       DEPARTMENT: Information_Security
4-cht-upgrade-service-1  |       EMAIL: domains@medic.org
4-cht-upgrade-service-1  |       LOCALITY: San_Francisco
4-cht-upgrade-service-1  |       ORGANISATION: medic
4-cht-upgrade-service-1  |       SSL_CERT_FILE_PATH: /etc/nginx/private/cert.pem
4-cht-upgrade-service-1  |       SSL_KEY_FILE_PATH: /etc/nginx/private/key.pem
4-cht-upgrade-service-1  |       STATE: California
4-cht-upgrade-service-1  |     image: public.ecr.aws/s5s3h4s7/cht-nginx:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  |     logging:
4-cht-upgrade-service-1  |       driver: local
4-cht-upgrade-service-1  |       options:
4-cht-upgrade-service-1  |         max-file: '20'
4-cht-upgrade-service-1  |         max-size: 50m
4-cht-upgrade-service-1  |     networks:
4-cht-upgrade-service-1  |       cht-net: null
4-cht-upgrade-service-1  |     ports:
4-cht-upgrade-service-1  |     - published: 80
4-cht-upgrade-service-1  |       target: 80
4-cht-upgrade-service-1  |     - published: 443
4-cht-upgrade-service-1  |       target: 443
4-cht-upgrade-service-1  |     volumes:
4-cht-upgrade-service-1  |     - cht-ssl:/etc/nginx/private:rw
4-cht-upgrade-service-1  |   sentinel:
4-cht-upgrade-service-1  |     depends_on:
4-cht-upgrade-service-1  |       haproxy:
4-cht-upgrade-service-1  |         condition: service_started
4-cht-upgrade-service-1  |     environment:
4-cht-upgrade-service-1  |       API_HOST: api
4-cht-upgrade-service-1  |       COUCH_URL: http://admin:password@haproxy:5984/medic
4-cht-upgrade-service-1  |     image: public.ecr.aws/s5s3h4s7/cht-sentinel:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  |     logging:
4-cht-upgrade-service-1  |       driver: local
4-cht-upgrade-service-1  |       options:
4-cht-upgrade-service-1  |         max-file: '20'
4-cht-upgrade-service-1  |         max-size: 50m
4-cht-upgrade-service-1  |     networks:
4-cht-upgrade-service-1  |       cht-net: null
4-cht-upgrade-service-1  | version: '3.9'
4-cht-upgrade-service-1  | volumes:
4-cht-upgrade-service-1  |   cht-ssl: {}
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | The COUCHDB_UUID variable is not set. Defaulting to a blank string.
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | networks:
4-cht-upgrade-service-1  |   cht-net:
4-cht-upgrade-service-1  |     name: cht-net
4-cht-upgrade-service-1  | services:
4-cht-upgrade-service-1  |   couchdb:
4-cht-upgrade-service-1  |     environment:
4-cht-upgrade-service-1  |       COUCHDB_LOG_LEVEL: error
4-cht-upgrade-service-1  |       COUCHDB_PASSWORD: password
4-cht-upgrade-service-1  |       COUCHDB_SECRET: secret
4-cht-upgrade-service-1  |       COUCHDB_USER: admin
4-cht-upgrade-service-1  |       COUCHDB_UUID: ''
4-cht-upgrade-service-1  |       SVC_NAME: couchdb
4-cht-upgrade-service-1  |     image: public.ecr.aws/s5s3h4s7/cht-couchdb:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  |     logging:
4-cht-upgrade-service-1  |       driver: local
4-cht-upgrade-service-1  |       options:
4-cht-upgrade-service-1  |         max-file: '20'
4-cht-upgrade-service-1  |         max-size: 50m
4-cht-upgrade-service-1  |     networks:
4-cht-upgrade-service-1  |       cht-net: null
4-cht-upgrade-service-1  |     restart: always
4-cht-upgrade-service-1  |     volumes:
4-cht-upgrade-service-1  |     - /Users/marialorenarodriguezviruel/medic-workspace/docker-files/#20/cht-core/srv:/opt/couchdb/data:rw
4-cht-upgrade-service-1  |     - cht-credentials:/opt/couchdb/etc/local.d:rw
4-cht-upgrade-service-1  | version: '3.9'
4-cht-upgrade-service-1  | volumes:
4-cht-upgrade-service-1  |   cht-credentials: {}
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | .IsADirectoryError: [Errno 21] Is a directory: '/docker-compose/srv'
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | The COUCHDB_UUID variable is not set. Defaulting to a blank string.
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating volume "4-test-upgrade-service_cht-ssl" with default driver
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating volume "4-test-upgrade-service_cht-credentials" with default driver
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Pulling healthcheck (public.ecr.aws/s5s3h4s7/cht-haproxy-healthcheck:4.0.0-7848-add-gh-action-for-staging-urls)...
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | 4.0.0-7848-add-gh-action-for-staging-urls: Pulling from s5s3h4s7/cht-haproxy-healthcheck
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Digest: sha256:68f229a1c4324528e04404dfe980b1634df2c874d5c105d0ce769b77e362d035
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Status: Downloaded newer image for public.ecr.aws/s5s3h4s7/cht-haproxy-healthcheck:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Pulling haproxy (public.ecr.aws/s5s3h4s7/cht-haproxy:4.0.0-7848-add-gh-action-for-staging-urls)...
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | 4.0.0-7848-add-gh-action-for-staging-urls: Pulling from s5s3h4s7/cht-haproxy
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Digest: sha256:db715b243c7152ec577efb86c1147800c83c6733d4fb62632592e3fb50b27071
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Status: Downloaded newer image for public.ecr.aws/s5s3h4s7/cht-haproxy:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Pulling couchdb (public.ecr.aws/s5s3h4s7/cht-couchdb:4.0.0-7848-add-gh-action-for-staging-urls)...
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | 4.0.0-7848-add-gh-action-for-staging-urls: Pulling from s5s3h4s7/cht-couchdb
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Digest: sha256:72f14419a0ef5c86b67d84ab19fd1b0184c08fece1495e813ee212b875a421ac
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Status: Downloaded newer image for public.ecr.aws/s5s3h4s7/cht-couchdb:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Pulling api (public.ecr.aws/s5s3h4s7/cht-api:4.0.0-7848-add-gh-action-for-staging-urls)...
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | 4.0.0-7848-add-gh-action-for-staging-urls: Pulling from s5s3h4s7/cht-api
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Digest: sha256:d8c65aaa11a753a2af17acc8e88e9192add1c7ef390d69132a24a9c50d6c0a8e
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Status: Downloaded newer image for public.ecr.aws/s5s3h4s7/cht-api:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Pulling nginx (public.ecr.aws/s5s3h4s7/cht-nginx:4.0.0-7848-add-gh-action-for-staging-urls)...
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | 4.0.0-7848-add-gh-action-for-staging-urls: Pulling from s5s3h4s7/cht-nginx
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Digest: sha256:57a5469c31e4e5a29560131aff433ad123d958744c690ccb9b42c23e35441cf4
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Status: Downloaded newer image for public.ecr.aws/s5s3h4s7/cht-nginx:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Pulling sentinel (public.ecr.aws/s5s3h4s7/cht-sentinel:4.0.0-7848-add-gh-action-for-staging-urls)...
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | 4.0.0-7848-add-gh-action-for-staging-urls: Pulling from s5s3h4s7/cht-sentinel
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Digest: sha256:24b0d5615751e4d6ba5761b66f56303c3f7bea07c6fc1f6c876e23a63f34443d
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Status: Downloaded newer image for public.ecr.aws/s5s3h4s7/cht-sentinel:4.0.0-7848-add-gh-action-for-staging-urls
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_haproxy_1 ... 
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_couchdb_1     ... 
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_healthcheck_1 ... 
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_healthcheck_1 ... done
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_haproxy_1     ... done
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_api_1         ... 
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_sentinel_1    ... 
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_couchdb_1     ... done
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_sentinel_1    ... done
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_api_1         ... done
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_nginx_1       ... 
4-cht-upgrade-service-1  | 
4-cht-upgrade-service-1  | Creating 4-test-upgrade-service_nginx_1       ... done
```
</details>

- I can access using admin and password, but not the user and password defined in the .env file.

**Comment by mrjones-plip** [comment]
@lorerod - thanks so much for the testing!  Great feedback here.

I found two possible bugs, one with the `.env` not liking the `${PWD}` and another that we've `404`ed the compose files.  I've made some updates to the readme.

That said, I was unable to reproduce your error of your different user and password not working.  Maybe you ran `docker compose up` with the old login and password (`admin`/`password`) and then changed the `.env` file and ran  `docker compose up` again?  If yes, the login and password are set on first run and then can only be changed in the web GUI.

Can you try destroying your containers & storage volumes (keep the images), delete your compose files, and try again with the updated steps?  You can [preview the readme here](https://github.com/medic/cht-upgrade-service/tree/mrjones-example-run-readme#example-usage). Be sure to change `COUCHDB_USER` and `COUCHDB_PASSWORD` before you do the first run of `docker compose up`.

Thanks thanks!

**Review by garethbowen — APPROVED** [review]
LGTM!

Sorry I missed this review request earlier!

**Comment by lorerod** [comment]
>
> Can you try destroying your containers & storage volumes (keep the images), delete your compose files, and try again with the updated steps? You can [preview the readme here](https://github.com/medic/cht-upgrade-service/tree/mrjones-example-run-readme#example-usage). Be sure to change `COUCHDB_USER` and `COUCHDB_PASSWORD` before you do the first run of `docker compose up`.
> 
> Thanks thanks!

@mrjones-plip Sorry I missed this! I tried again as you suggested and I was able to login with user and password set in `.env`. Thank you!

**Comment by mrjones-plip** [comment]
no worries @lorerod !  Thanks for circling back and confirming the fix worked.

**Pull request merged**
