### PR TITLE
fix(#40): Retry on rate exceeded errors on `up`

### PR DESCRIPTION
**Pull request by dianabarsan**

### CODE REVIEW

**Review by garethbowen — CHANGES_REQUESTED** [review]
So nice! Love the reuse.

Can you also add a `console.log` somewhere in the `composeCommand` function, like line 19, to output the command that's being executed? That'd make debugging this easier next time.

**Comment by dianabarsan** [comment]
> Can you also add a console.log somewhere in the composeCommand function, like line 19, to output the command that's being executed? That'd make debugging this easier next time.

Done!

**Review by garethbowen — APPROVED** [review]
Awesome!

**Comment by garethbowen** [comment]
Merging to unblock my cht-core PR!

**Pull request merged**
